# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Utilise une version stable récente
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # Tu peux ajouter d'autres hooks de ce dépôt ici si besoin
