repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # ou la version que tu utilises
    hooks:
      - id: trailing-whitespace
        args: [--no-markdown-linebreak-ext] # Un argument possible, mais peut ne pas cibler le problème
      - id: end-of-file-fixer
